version: "3.9" 
services:
  payment-service:
    build: 
      context: ./payment-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=setel_db
      - PORT=3001
    depends_on:
      - db

  order-service:
    build: 
      context: ./order-service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=setel_db
      - PORT=3000
      - XAMOUNT=600000
      - PAYMENT_HOST=http://payment-service:3001
    depends_on:
      - db
      
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=setel_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5